### ISSUE TITLE
Determining values for parameters

### ISSUE THREAD

**Issue by mictadlo** [yechengxi/SparseAssembler#1]
Hi,
How do I determine values for  the following parameters?
- NodeCovTh
- EdgeCovTh
- LD
- PathCovTh

Thank you in advance.

Best wishes,

Mic

**Comment by yechengxi** [comment]
For the first run, LD must be 0, NodeCovTh 1 EdgeCovTh 0 are the default settings.
You may tune these values after your initial assembly, by setting LD 1 and change the rest values.
