### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by s-yazar** [yechengxi/SparseAssembler#2]
Hi Chengxi,

Which output files should I have after running the following command on my data?

./SparseAssembler GS GENOME_SIZE NodeCovTh FALSE_KMER_THRESHOLD EdgeCovTh FALSE_EDGE_THRESHOLD k KMER_SIZE g SKIP_SIZE f YOUR_FASTA_OR_FASTQ_FILE1 f YOUR_FASTA_OR_FASTQ_FILE2 f YOUR_FASTA_OR_FASTQ_FILE3_ETC

My job run got completed but I am not sure if I have all the correct output files.

Thank you,
Seyhan

**Comment by yechengxi** [comment]
You need the Contigs.txt file.
