### ISSUE TITLE
no output generated

### ISSUE THREAD

**Issue by TinaH10** [yechengxi/SparseAssembler#3]
Hello,

I ran SparseAssembler with the following command:

#!/bin/sh
#BSUB -q mpi
#BSUB -W 48:00
#BSUB -o 27_Sparse.OUT
#BSUB -e 27_Sparse.ERR
#BSUB -R 'span[hosts=1]'
#BSUB -n 10

/usr/users/bharr/SparseAssembler/compiled/SparseAssembler g 25 k 51 LD 0 GS 9000000000 i1 TP-BH27_S2_L006_R1_001.fastq i2 TP-BH27_S2_L006_R1_001.fastq

This is a paired-end Illumina dataset, around 80x coverage of a bird genome approximate size 1.2Gb. The assembler runs and gives all sorts of outfiles, but most of those are empty. 

-rw------- 1 bharr MPLM          0 Mar 13 21:35 27_Sparse.ERR
-rw------- 1 bharr MPLM       8557 Mar 13 21:35 27_Sparse.OUT
-rw------- 1 bharr MPLM          0 Mar 13 21:06 Asm_HT_content
-rw------- 1 bharr MPLM 1565217417 Mar 13 21:35 Asm_HT_idx.txt
-rw------- 1 bharr MPLM         23 Mar 13 20:37 Assembly_Log.txt
-rw------- 1 bharr MPLM         15 Mar 13 20:37 BasesCount.txt
-rw------- 1 bharr MPLM          2 Mar 13 21:35 ContigGraph.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Contigs_Cov.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Contigs_HP.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Contigs_info.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Contigs_Len.txt
-rw------- 1 bharr MPLM         17 Mar 13 21:35 ContigsLog.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Contigs.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 Cov_HistContigs.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 CovHist.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 EdgeCovHist.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 MergeHT_content
-rw------- 1 bharr MPLM   31304377 Mar 13 21:35 MergeHT_idx.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 nLB_Contigs.txt
-rw------- 1 bharr MPLM          0 Mar 13 21:35 nRB_Contigs.txt

I don't know what is going on. Do you have a suggestion?

Thank you very much!

**Comment by TinaH10** [comment]
so sorry, found the mistake!!

**Comment by olechnwin** [comment]
Can you please post in here what was your mistake? I have the same problem. After running sparseassembler, I have files with size 0. I can't figure out what was wrong. Thanks!

This is my command:
`SparseAssembler g 10 k 51 LD 0 GS 9600000000 NodeCovTh 1 EdgeCovTh 0 selectedReads/Illumina_30x.fastq`

**Comment by olechnwin** [comment]
In case other people is looking for the answer here, I figured out that the problem was because I did not have the '**f**' before specifying the reads file. The correct command is:

`SparseAssembler g 10 k 51 LD 0 GS 9600000000 NodeCovTh 1 EdgeCovTh 0 f selectedReads/Illumina_30x.fastq`

Hope this helps someone
