### ISSUE TITLE
Scan finished. Error! K-mer size too large!

### ISSUE THREAD

**Issue by kubu4** [yechengxi/SparseAssembler#4]
I'm getting assembly failures with this error message. I've determined ideal kmer size using kmergenie with my datasets (k = 131), but SparseAssembler spits out this error message.

Here's my SparseAssembler command (I have not included the list of paired end fastq files, due to the large number of files):

```/gscratch/srlab/programs/SparseAssembler/SparseAssembler \
LD 0 \
NodeCovTh 1 \
EdgeCovTh 0 \
k 131 \
g 15 \
PathCovTh 100 \
GS 2200000000 \
```

If I reduce the kmer size (e.g. k 101), it'll run without issue. Just wondering what the maximum kmer size is for SparseAssembler and also wondering why it won't accept k = 131. Thanks.

**Comment by yechengxi** [comment]
Right, because the largest supported k-mer size is 127.

**Comment by kubu4** [comment]
Thanks for responding. I've also gotten this failure, using the same data sets, with kmer settings set to 117 and 111.
