### ISSUE TITLE
Is SparseAssembler suitable for high heterozygous rate plant genome?

### ISSUE THREAD

**Issue by xiekunwhy** [yechengxi/SparseAssembler#8]
Hi,

I am looking for some assemblers to assemble a high heterozygous rate plant genome(diploid, het rate > 2%, haplotype genome size ~3.6G).
And I want to know how to use SparseAssembler to assemble such a genome.

Best wishes,
Kun

**Comment by yechengxi** [comment]
You can use it as usual.  Just the assembly quality can be lower. Try to focus more on the parameters related with bubble merging.
