### ISSUE TITLE
kmer size and minimum read length

### ISSUE THREAD

**Issue by pdimens** [yechengxi/SparseAssembler#9]
Out of curiosity, what does SparseAssembler do when the kmer value is set higher than the length of some reads? For example, if k = 90 and your reads are 50bp and higher, does SparseAssembler automatically set the minimum usable read length to be >= k? Or would it be more performant to specify a read length cutoff?

**Comment by yechengxi** [comment]
There is a quality check and the short reads will be thrown away.
